/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.0
 * $ npm run postdb
 *
 */


export type Json = unknown;

// Table states
export interface States {
  state: string;
  created_at: Date;
}
export interface StatesInput {
  state: string;
  created_at?: Date;
}
const states = {
  tableName: 'states',
  columns: ['state', 'created_at'],
  requiredForInsert: ['state'],
  primaryKey: 'state',
  foreignKeys: {},
  $type: null as unknown as States,
  $input: null as unknown as StatesInput
} as const;

// Table users
export interface Users {
  id: string;
  login: string;
  display_name: string;
  access_token: string | null;
  refresh_token: string | null;
  scope: string[] | null;
  expires: Date | null;
}
export interface UsersInput {
  id: string;
  login: string;
  display_name: string;
  access_token?: string | null;
  refresh_token?: string | null;
  scope?: string[] | null;
  expires?: Date | null;
}
const users = {
  tableName: 'users',
  columns: ['id', 'login', 'display_name', 'access_token', 'refresh_token', 'scope', 'expires'],
  requiredForInsert: ['id', 'login', 'display_name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Users,
  $input: null as unknown as UsersInput
} as const;


export interface TableTypes {
  states: {
  select: States;
  input: StatesInput;
  };
  users: {
  select: Users;
  input: UsersInput;
  };
}

export const tables = {
  states,
  users,
}
